services:
  postgres:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PUBLIC_PORT}:5432"

volumes:
  postgres_data:
