services:
  postgres:
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .postgres.env
    ports:
      - "${PUBLIC_PORT}:5432"

volumes:
  postgres_data:
